config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
                    has_secure_password
  validates :password, length: { minimum: 6 }
  has_many :blogs
  has_many :feeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper 
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blogs_path
    else
      render :new
    end
  end
  
  def confirm
    @blog = Blog.new(blog_params)
  end

  def show
    @blog = Blog.find(params[:id])
  end
      
  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "更新しました"
    else
      render :new
    end

  end
  
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger]="ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice]= "ログアウトしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end


  def show
      @user = User.find(params[:id])
  end  


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する</h3>

<%= form_with(model: @blog, local: true,) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <p>画像:<%= image_tag @blog.image.url %></p>
  <%= form.submit  "登録する" %>
<% end %>

app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

app/views/blogs/edit.html.erb
<h1>blogs_new</h1>

<%= form_with(model: @blog, local: true) do |form| %>
    <div class="blog_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div class="blog_content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <%= form.submit %>
  <% end %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>ユーザー</th>
    <th>詳細</th>
    <th>編集</th>
    <th>削除</th>
  </tr>

<% @blogs.each do |blog| %>
    <tr>
      <th><%= blog.title %></th>
      <th><%= blog.user.name %></th>
      <th><%= link_to "●", blog_path(blog.id) %></th>
      <th><%= link_to "●", edit_blog_path(blog.id) %></th>
      <th><%= link_to "●", blog_path(blog.id), method: :delete%></th>
    </tr>
  <%end%>
</table>
<p><%= link_to "新規投稿",new_blog_path %></p>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true, url: confirm_blogs_path) do |form| %>
    <div class="blog_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    <div class="blog_content">
      <%= form.label :content %>
      <%= form.text_field :content %>
    </div>
    <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
    <%= form.submit %>
  <% end %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>

<p>
  <strong>画像:</strong>
  <%= image_tag @blog.image.url %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h4>友達つながりアプリケーション</h4>
    </header>
      
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

  <% if log_in? %>
    <%= link_to "プロフィール", user_path(current_user.id) %>
    <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
  <% else %>
    <%= link_to "新規登録", new_user_path %>
    <%= link_to "ログイン", new_session_path %>
  <% end %>
    <%= yield %>
  </body>

app/views/users/new.html.erb
<h1>アカウント作成</h1>

<h1>user New</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :ユーザー名 %>
  <%= f.text_field :name %>

  <p><%= f.label :Eメール %>
  <%= f.email_field :email %></p>

  <p><%= f.label :パスワード %>
  <%= f.password_field :password %></p>

  <p><%= f.label :パスワード（確認） %>
  <%= f.password_field :password_confirmation %></p>

  <p><%= f.submit "アカウント作成" %></p>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<%= link_to "ブログを投稿する",blogs_path %>